config/routes.rb
AAAWebsite::Application.routes.draw do
  devise_for :members

  resources :events

  root :to => 'aaa_core#index'
  match '/shop', :to => 'aaa_core#shop'
  match '/discussion', :to => 'aaa_core#discussion'
  

  

end

app/models/event.rb
class Event < ActiveRecord::Base

	attr_accessible :title, :date, :description
	validates_presence_of :title, :date, :description
	validates_uniqueness_of :title
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/aaa_core_controller.rb
class AaaCoreController < ApplicationController
  def index
  	@title = "Home"
  end

  def shop
    @title = "Shop"
  end

  def discussion
  	@title = "Discussion Forum"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :require_authentication, :except => [:index, :show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
  
  private
  def require_authentication
    
  end
end

app/helpers/aaa_core_helper.rb
module AaaCoreHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = "Allotments Association"
		if @title.nil?
			base_title
		else
			"#{base_title}| #{@title}"
		end
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/aaa_core/discussion.html.erb
<h1>AaaCore#discussion</h1>
<p>Find me in app/views/aaa_core/discussion.html.erb</p>

app/views/aaa_core/events.html.erb
<h1>AaaCore#events</h1>
<p>Find me in app/views/aaa_core/events.html.erb</p>

app/views/aaa_core/index.html.erb
<h1>AaaCore#index</h1>
<p>Find me in app/views/aaa_core/index.html.erb</p>

app/views/aaa_core/shop.html.erb
<h1>AaaCore#shop</h1>
<p>Find me in app/views/aaa_core/shop.html.erb</p>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.date %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_footer.html.erb
<footer>
  &copy <%= Time.now.year %> Ashtead Allotment's Association
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1> Ashtead Allotments Association</h1>
  <h2> Healthy Eating and Exercise preserve Life's Balance</h2>
</header>

app/views/layouts/_navigation.html.erb
<nav>
<ul>
<li> <%= link_to "Home", root_path %></li>
<li> <%= link_to "Events", events_path %></li>
<li> <%= link_to "Discussion", discussion_path %></li>
<li> <%= link_to "Shop", shop_path %></li>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=title%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= render 'layouts/navigation' %>

	<section class="sidebar" id="right">
	  <% if user_signed_in? %>
	    Signed in as <%= current_user.email %>:
	    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	  	
	  <% else %>
	    <%= link_to "Sign up", new_user_registration_path %> or 
	    <%= link_to "Sign in", new_user_session_path %>
	  	
	  <% end %>
	</section>


<%= yield %>

    <%= render 'layouts/footer'%>
</body>
</html>